n = str(input('digite seu nome : ')).strip()
print('Muito prazer em te conhecer!')
nome = n.split()
print('Seu primeiro nome é {} '.format(nome[0]))
print('E seu ultimo nome é {} '.format(nome[len(nome)]-1))